#!/bin/bash


echo "Cleaning logs and output files from previous runs..."

rm -f precice-FLUID-events.json \
      precice-Solid-events.json \
      precice-FLUID-iterations.log \
      precice-Solid-convergence.log \
      precice-Solid-iterations.log \
      precice-FLUID-events-summary.log \
      precice-STRUCTUR-events-summary.log \
      Postproc/*.vtk \

rm -r precice-run/
rm -rfv precice-Solid-events-summary.log

echo "Cleaning successful!"
