#!/bin/bash


echo "Cleaning logs and output files from previous runs..."

rm -f precice-FLUID-events.json \
      precice-STRUCTURE-events.json \
      precice-FLUID-iterations.log \
      precice-STRUCTURE-convergence.log \
      precice-STRUCTURE-iterations.log \
      precice-FLUID-events-summary.log \
      precice-STRUCTUR-events-summary.log
      Postproc/*.vtk \
      Fluid.log \
      Structure.log

rm -r precice-run/

echo "Cleaning successful!"
