#!/bin/bash

# This script runs the FluidSolver and SolidSolver binaries of the C++ variant
#
# Terminal output of both processes is redirected into two separate log files.
#
# Raises error if either solver returns nonzero exit code or the .log files
#   that capture output contain an error message.


# target directory in which the solvers are located
solverroot="./"
configfile="precice-config.xml"

# parameter values
N=100
tau=0.01
kappa=100


echo "Starting Fluid participant..."
${solverroot}FluidSolver ${solverroot}${configfile} $N $tau $kappa > Fluid.log 2>&1 &
pid1=$!

echo "Starting Solid participant..."
${solverroot}SolidSolver ${solverroot}${configfile} $N > Solid.log 2>&1 &
pid2=$!

echo ""
echo "Waiting for participants to finish..."
echo "(you may run 'tail -f Fluid.log' in another terminal to check the progress)"
wait $pid1
exitcode1=$?
echo "Fluid participant finished. Waiting for Solid participant..."
wait $pid2
exitcode2=$?
echo "Solid participant finished."

if [ $exitcode1 -ne 0 ] || [ $exitcode2 -ne 0 ] || [ "$(grep -c -E "error:" Fluid.log)" -ne 0 ] || [ "$(grep -c -E "error:" Solid.log)" -ne 0 ]; then
  echo ""
  echo "Something went wrong. See the Fluid.log and Solid.log files for more info."
  exit 1
else
  echo ""
  echo "Simulation completed successfully! Output files of the simulation were written to 'Postproc/out_fluid_*.vtk'."
fi

exit 0
